#!/usr/bin/env python3
# tools/finrl_adapter.py
"""
Lightweight FinRL policy adapter used by the orchestrator.

Purpose:
- Discover trained RL policy artifacts in a folder (recursively).
- Optionally load them (best-effort) to sanity-check they are readable.
- Produce a manifest JSON summarizing what was found.
- Exit 0 regardless (non-fatal), so the pipeline keeps moving.

This does NOT run an actual backtest/inference loop. You can extend
the "evaluate_policy" stub to add real scoring later.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

# joblib is the most common serializer for RL policies in many repos
try:
    import joblib  # type: ignore
except Exception:
    joblib = None


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def find_policy_files(root: Path) -> List[Path]:
    patterns = ("*.joblib", "*.pkl")
    found: List[Path] = []
    for pat in patterns:
        found += list(root.rglob(pat))
    return found


def try_load(path: Path) -> Dict[str, Any]:
    """
    Try loading a serialized policy. If joblib isn't available or the
    file can't be loaded, return metadata with error.
    """
    info: Dict[str, Any] = {
        "path": str(path),
        "size_bytes": path.stat().st_size if path.exists() else None,
        "loaded": False,
        "model_type": None,
        "error": None,
    }
    if joblib is None:
        info["error"] = "joblib_not_available"
        return info
    try:
        obj = joblib.load(path)
        info["loaded"] = True
        info["model_type"] = type(obj).__name__
        # Some policies carry attributes we might want to record
        for attr in ("algo", "gamma", "n_steps", "learning_rate"):
            if hasattr(obj, attr):
                info[attr] = getattr(obj, attr)
        return info
    except Exception as e:
        info["error"] = f"{type(e).__name__}: {e}"
        return info


def evaluate_policy(_obj: Any) -> Dict[str, Any]:
    """
    Placeholder. Return a dumb score so downstream tooling has a number.
    Replace with real evaluation if/when you integrate market data here.
    """
    return {
        "health_score": 0.5,  # constant placeholder
        "notes": "Placeholder evaluation; integrate backtest/inference to compute real metrics.",
    }


def main(argv: Optional[List[str]] = None) -> int:
    p = argparse.ArgumentParser(description="FinRL policy adapter (manifest generator)")
    p.add_argument("--policies", required=True, help="Folder containing FinRL policies (scanned recursively)")
    p.add_argument("--algo", default=None, help="Algorithm label (e.g., PPO, A2C). Optional metadata.")
    p.add_argument("--out", default="reports/finrl_eval", help="Directory to write the manifest JSON")
    args = p.parse_args(argv)

    root = Path(args.policies).expanduser().resolve()
    out_dir = Path(args.out).expanduser().resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    manifest: Dict[str, Any] = {
        "generated_at": utc_now(),
        "algo": args.algo,
        "policies_root": str(root),
        "host_cwd": str(Path.cwd()),
        "items": [],
        "summary": {},
        "notes": [
            "This file is generated by tools/finrl_adapter.py",
            "Adapter is non-fatal and returns 0 to keep the pipeline moving.",
            "Replace evaluate_policy(...) to add real metrics.",
        ],
    }

    if not root.exists() or not root.is_dir():
        manifest["summary"] = {"found": 0, "loaded_ok": 0}
        # Still write an empty manifest so the step is traceable
        out_path = out_dir / f"finrl_manifest_{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')}.json"
        with open(out_path, "w", encoding="utf-8") as f:
            json.dump(manifest, f, indent=2)
        print(f"[finrl-adapter] policies directory not found: {root}", file=sys.stderr)
        print(f"[finrl-adapter] empty manifest written to: {out_path}")
        return 0

    files = find_policy_files(root)
    loaded_ok = 0
    for fp in files:
        item = try_load(fp)
        if item.get("loaded"):
            loaded_ok += 1
            # Run placeholder evaluator
            item["evaluation"] = evaluate_policy(None)
        manifest["items"].append(item)

    manifest["summary"] = {
        "found": len(files),
        "loaded_ok": loaded_ok,
        "failed": len(files) - loaded_ok,
    }

    out_path = out_dir / f"finrl_manifest_{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')}.json"
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2)
    print(f"[finrl-adapter] Manifest written: {out_path}")
    print(f"[finrl-adapter] Found={len(files)} LoadedOK={loaded_ok} Failed={len(files)-loaded_ok}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
